import re
import sqlite3
from datetime import datetime

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from countries import get_country_config
from typing import Optional, List
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from config import DB_PATH, MODEL_PATH

# ── LLM client (lazy init) ──────────────────────────────────────────────────
_openai_client = None

def get_openai():
    global _openai_client
    if _openai_client is None:
        import openai
        _openai_client = openai.OpenAI()  # reads OPENAI_API_KEY from env
    return _openai_client

CURRENT_YEAR = datetime.now().year

# ── Thresholds & constants ───────────────────────────────────────────────────
# Confidence: how tightly comparable cars are priced (spread of log-prices %)
CONFIDENCE_HIGH_THRESHOLD  = 12   # spread < 12% → "Very accurate"
CONFIDENCE_MED_THRESHOLD   = 22   # spread < 22% → "Accurate", else "Not accurate"
CONFIDENCE_MIN_SAMPLES     = 10   # minimum comparable cars needed
CONFIDENCE_FALLBACK_SPREAD = 40   # assumed spread when no comparables found

# Verdict: SNR thresholds (signal-to-noise = |diff_pct| / spread)
SNR_STRONG = 2.0                  # high confidence in over/underpriced
SNR_LIKELY = 1.0                  # likely over/underpriced
SNR_POSSIBLE = 0.5                # possibly over/underpriced
VERDICT_FAIR_PCT = 5              # |diff_pct| < 5% → always "Fair price"
VERDICT_SIMPLE_PCT = 15           # simple over/underpriced threshold (legacy)

# ── Load model once at startup ────────────────────────────────────────────────
# Loads lazily so the app starts cleanly even before pipeline.joblib is uploaded
import os
_pipeline = None

def get_pipeline():
    global _pipeline
    if _pipeline is None:
        if not os.path.exists(MODEL_PATH):
            from fastapi import HTTPException
            raise HTTPException(status_code=503, detail="Model not loaded yet — upload pipeline.joblib to /data/")
        _pipeline = joblib.load(MODEL_PATH)
    return _pipeline

# ── Rate limiting ─────────────────────────────────────────────────────────────
limiter = Limiter(key_func=get_remote_address, default_limits=["200/hour"])

app = FastAPI(title="Car Price Predictor")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Range lookup (replaces old confidence system) ────────────────────────────
# Loaded from range_lookup.json generated by train.py.  Each entry is the 80th
# percentile of |prediction_error_%|, so ~80% of actual prices fall within
# ±range% of the predicted price.
_range_lookup = None

def _load_range_lookup():
    global _range_lookup
    if _range_lookup is not None:
        return _range_lookup
    import json
    lookup_path = os.path.join(os.path.dirname(MODEL_PATH), "range_lookup.json")
    if not os.path.exists(lookup_path):
        # Fallback: try same dir as api.py
        lookup_path = os.path.join(os.path.dirname(__file__), "range_lookup.json")
    try:
        with open(lookup_path) as f:
            _range_lookup = json.load(f)
    except FileNotFoundError:
        _range_lookup = {"trim": {}, "model": {}, "make": {}, "global": 12.0}
    return _range_lookup


def get_range_pct(trim_id: Optional[str], make: str, model: str) -> dict:
    """Look up the prediction error range for a car.

    Returns {"range_pct": float, "basis": str, "level": str}.
    range_pct is the ±% around predicted price that covers ~80% of actual prices.
    """
    lookup = _load_range_lookup()

    # Tier 1: trim_id
    if trim_id and trim_id != "Unknown" and trim_id in lookup.get("trim", {}):
        pct = lookup["trim"][trim_id]
        basis = "trim"
    # Tier 2: make + model
    elif f"{make}|{model}" in lookup.get("model", {}):
        pct = lookup["model"][f"{make}|{model}"]
        basis = "model"
    # Tier 3: make
    elif make in lookup.get("make", {}):
        pct = lookup["make"][make]
        basis = "make"
    # Tier 4: global
    else:
        pct = lookup.get("global", 12.0)
        basis = "global"

    # Level thresholds (for badge display)
    if pct <= 10:
        level = "high"
    elif pct <= 18:
        level = "medium"
    else:
        level = "low"

    return {"range_pct": pct, "basis": basis, "level": level}


# Legacy wrapper for backward compatibility
def get_confidence(trim_id, make, model, year=None, mileage=None,
                   fuel=None, power_kw=None):
    """Maps the new range system to the old confidence response shape."""
    r = get_range_pct(trim_id, make, model)
    pct = r["range_pct"]
    level = r["level"]
    labels = {"high": "Very accurate", "medium": "Accurate", "low": "Not accurate"}
    return {
        "spread_pct":   pct,
        "sample_count": None,  # no longer used
        "basis":        r["basis"],
        "level":        level,
        "label":        labels[level],
        "range_pct":    pct,
    }


# ── Verdict helper ───────────────────────────────────────────────────────────
def compute_final_verdict(diff_pct: float, confidence: dict) -> dict:
    """SNR-based verdict used by both /predict and /predict/batch.

    Uses range_pct (model error range) as the noise floor.  A diff that exceeds
    the model's typical error is a meaningful signal.
    """
    range_pct = confidence.get("range_pct") or confidence.get("spread_pct") or CONFIDENCE_FALLBACK_SPREAD
    snr = abs(diff_pct) / range_pct if range_pct > 0 else 0

    if abs(diff_pct) < VERDICT_FAIR_PCT:
        return {"label": "Fair price", "color": "#2563eb"}
    elif diff_pct < 0:  # underpriced signal
        if   snr > SNR_STRONG:   return {"label": "Great deal",           "color": "#16a34a"}
        elif snr > SNR_LIKELY:   return {"label": "Likely underpriced",   "color": "#65a30d"}
        elif snr > SNR_POSSIBLE: return {"label": "Possibly underpriced", "color": "#84cc16"}
        else:                     return {"label": "Fair price",           "color": "#2563eb"}
    else:               # overpriced signal
        if   snr > SNR_STRONG:   return {"label": "Overpriced",           "color": "#dc2626"}
        elif snr > SNR_LIKELY:   return {"label": "Likely overpriced",    "color": "#ea580c"}
        elif snr > SNR_POSSIBLE: return {"label": "Possibly overpriced",  "color": "#f97316"}
        else:                     return {"label": "Fair price",           "color": "#2563eb"}


# ── Feature builder (must match train.py features exactly) ────────────────────
def _build_features(car) -> dict:
    """Build feature dict matching the model's expected columns."""
    car_age = CURRENT_YEAR - car.year
    fuel = car.fuel or "Unknown"
    return {
        "car_age":         car_age,
        "mileage":         car.mileage,
        "power_kw":        car.power_kw,
        "range_km":        car.range_km,
        "mileage_per_year": car.mileage / max(1, car_age),
        "is_electric":     int(bool(re.match(r"(?i)^elektr", fuel))),
        "is_hybrid":       int(bool(re.search(r"(?i)elektro/|hybrid|/elektr", fuel))),
        "make":            car.make,
        "model":           car.model,
        "trim_id":         car.trim_id       or "Unknown",
        "variant_id":      car.variant_id    or "Unknown",
        "generation_id":   car.generation_id or "Unknown",
        "fuel":            fuel,
        "transmission":    car.transmission,
        "seller_type":     car.seller_type   or "Unknown",
        "country":         (getattr(car, "country", None) or "NL").upper(),
    }


# ── Request schemas ───────────────────────────────────────────────────────────
class CarInput(BaseModel):
    make: str
    model: str
    year: int
    mileage: int
    fuel: str
    transmission: str
    power_kw:      Optional[int] = None
    range_km:      Optional[int] = None
    trim_id:       Optional[str] = None
    variant_id:    Optional[str] = None
    generation_id: Optional[str] = None
    body_type:     Optional[str] = None
    colour:        Optional[str] = None
    seller_type:   Optional[str] = None
    actual_price:  Optional[int] = None
    country:       Optional[str] = "NL"


class CarBatchItem(BaseModel):
    id: str
    make: str
    model: str
    year: int
    mileage: int
    fuel: str
    transmission: str
    power_kw:      Optional[int] = None
    range_km:      Optional[int] = None
    trim_id:       Optional[str] = None
    variant_id:    Optional[str] = None
    generation_id: Optional[str] = None
    body_type:     Optional[str] = None
    colour:        Optional[str] = None
    seller_type:   Optional[str] = None
    actual_price:  Optional[int] = None
    country:       Optional[str] = "NL"


# ── Privacy policy ────────────────────────────────────────────────────────────
@app.get("/privacy", response_class=HTMLResponse)
def privacy():
    return """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy — AutoScout24 Price Analyser</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           max-width: 680px; margin: 60px auto; padding: 0 24px;
           color: #1a1a1a; line-height: 1.7; }
    h1 { font-size: 1.6rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.1rem; margin-top: 2rem; }
    p, ul { margin: 0.5rem 0; }
    ul { padding-left: 1.4rem; }
    a { color: #e84118; }
    .updated { color: #888; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>Privacy Policy</h1>
  <p class="updated">AutoScout24 Price Analyser &mdash; last updated March 2026</p>

  <h2>What data is collected</h2>
  <p>The extension reads car listing data (make, model, year, mileage, fuel type,
  transmission, power, and asking price) directly from AutoScout24 pages you visit.
  This data is sent to our prediction API solely to calculate an estimated market value.</p>
  <p>We do <strong>not</strong> collect:</p>
  <ul>
    <li>Any personally identifiable information</li>
    <li>Your browsing history</li>
    <li>Any data unrelated to the car listings on the current page</li>
  </ul>

  <h2>How data is used</h2>
  <p>Car listing data is sent to this API to generate a price prediction. The data is used
  only to produce the prediction shown to you and is not stored, logged, or shared.</p>

  <h2>Third parties</h2>
  <p>No data is shared with any third party. The prediction API is operated by the extension developer.</p>

  <h2>Contact</h2>
  <p>Questions? Open an issue at
  <a href="https://github.com/qwillemse/autoscout-analyser">github.com/qwillemse/autoscout-analyser</a>.</p>
</body>
</html>"""


# ── Health check (always returns 200 so Railway can start) ────────────────────
@app.get("/health")
def health():
    return {"status": "ok"}


# ── Stats endpoint ────────────────────────────────────────────────────────────
@app.get("/stats")
def stats():
    try:
        con = sqlite3.connect(DB_PATH)
        count = con.execute("SELECT COUNT(*) FROM listings").fetchone()[0]
        con.close()
        return {"listing_count": count, "status": "ok"}
    except Exception:
        return {"listing_count": 0, "status": "db_not_loaded"}


# ── Batch predict endpoint ────────────────────────────────────────────────────
@app.post("/predict/batch")
@limiter.limit("20/minute")
def predict_batch(request: Request, cars: list[CarBatchItem]):
    if not cars:
        return []

    # Single predict call for all cars at once — much faster than looping
    features = pd.DataFrame([_build_features(car) for car in cars])

    predicted_prices = np.expm1(get_pipeline().predict(features)).astype(int)

    results = []
    for car, predicted_price in zip(cars, predicted_prices):
        result = {"id": car.id, "predicted_price": int(predicted_price)}
        if car.actual_price:
            diff_pct = (car.actual_price - predicted_price) / predicted_price * 100
            result["diff_pct"] = round(float(diff_pct), 1)
            confidence = get_confidence(car.trim_id, car.make, car.model,
                                        car.year, car.mileage,
                                        fuel=car.fuel, power_kw=car.power_kw)
            result["confidence"]    = confidence
            result["final_verdict"] = compute_final_verdict(diff_pct, confidence)
        results.append(result)
    return results


# ── Predict endpoint ──────────────────────────────────────────────────────────
@app.post("/predict")
@limiter.limit("60/minute")
def predict(request: Request, car: CarInput):
    features = pd.DataFrame([_build_features(car)])

    predicted_price = int(np.expm1(get_pipeline().predict(features)[0]))
    confidence = get_confidence(car.trim_id, car.make, car.model, car.year, car.mileage,
                               fuel=car.fuel, power_kw=car.power_kw)

    response = {
        "predicted_price": predicted_price,
        "confidence": confidence,
    }

    if car.actual_price is not None:
        diff_pct = (car.actual_price - predicted_price) / predicted_price * 100
        response["actual_price"] = car.actual_price
        response["diff_pct"]     = round(diff_pct, 1)
        response["diff_eur"]     = car.actual_price - predicted_price
        # Simple verdict for backwards compatibility
        if diff_pct > VERDICT_SIMPLE_PCT:
            response["verdict"] = "overpriced"
        elif diff_pct < -VERDICT_SIMPLE_PCT:
            response["verdict"] = "underpriced"
        else:
            response["verdict"] = "fair"
        response["final_verdict"] = compute_final_verdict(diff_pct, confidence)

    return response


# ── Explain endpoint (premium) ───────────────────────────────────────────────
class ExplainInput(BaseModel):
    make: str
    model: str
    year: int
    mileage: int
    fuel: str
    transmission: str
    power_kw:         Optional[int] = None
    predicted_price:  int
    actual_price:     int
    diff_pct:         float
    confidence_level: Optional[str] = None
    range_pct:        Optional[float] = None
    description:      Optional[str] = None
    equipment:        Optional[list[str]] = None
    photo_count:      Optional[int] = None
    previous_owners:  Optional[int] = None
    apk_date:         Optional[str] = None
    country:          Optional[str] = "nl"

@app.post("/explain")
@limiter.limit("10/minute")
def explain(request: Request, data: ExplainInput):
    car_age = CURRENT_YEAR - data.year
    mileage_per_year = round(data.mileage / max(car_age, 1))
    avg_mileage_per_year = 15_000  # rough NL average

    # Fetch average price for similar-year cars of same make/model
    avg_price = None
    try:
        con = sqlite3.connect(DB_PATH)
        row = con.execute(
            "SELECT AVG(price), COUNT(*) FROM listings WHERE make = ? AND model = ? AND year BETWEEN ? AND ?",
            (data.make, data.model, data.year - 2, data.year + 2),
        ).fetchone()
        con.close()
        if row and row[1] > 5:
            avg_price = int(row[0])
    except Exception:
        pass

    # Build listing details section if extras are available
    listing_details = ""
    if data.description or data.equipment or data.previous_owners is not None or data.apk_date:
        parts = []
        if data.previous_owners is not None:
            parts.append(f"- Previous owners: {data.previous_owners}")
        if data.apk_date:
            parts.append(f"- APK (MOT) valid until: {data.apk_date}")
        if data.photo_count:
            parts.append(f"- Photos: {data.photo_count}")
        if data.equipment:
            parts.append(f"- Equipment: {', '.join(data.equipment[:20])}")
        if data.description:
            # Truncate long descriptions
            desc = data.description[:500] + ("..." if len(data.description) > 500 else "")
            parts.append(f"- Seller description: {desc}")
        listing_details = "\n\nListing details:\n" + "\n".join(parts)

    # Country-specific context
    country_code = (data.country or "nl").lower()
    country_names = {"nl": "Dutch", "de": "German", "be": "Belgian", "at": "Austrian",
                     "fr": "French", "it": "Italian", "es": "Spanish", "lu": "Luxembourg"}
    country_name = country_names.get(country_code, "European")
    site_suffix = {"nl": "NL", "de": "DE", "be": "BE", "at": "AT",
                   "fr": "FR", "it": "IT", "es": "ES", "lu": "LU"}.get(country_code, "NL")

    # Range info
    range_text = f"±{data.range_pct}% (80% of similar cars fall within this range)" if data.range_pct else ""
    confidence_text = f"{data.confidence_level}" if data.confidence_level else "unknown"
    if range_text:
        confidence_text += f" — {range_text}"

    # Description context per country
    desc_context = ""
    if listing_details:
        if country_code == "nl":
            desc_context = """
IMPORTANT — Dutch market context for reading descriptions:
- "Eerste eigenaar in Nederland" means first DUTCH owner — the car was likely imported and had previous owners abroad. This is normal and NOT suspicious.
- "Sinds [year] ~X km" means the current owner drove X km since that year, NOT that total mileage is X km. The total mileage is always the number shown in the listing specs above.
- Replaced odometer/tellerunit means the DISPLAYED mileage may be wrong — the description usually states the real mileage. This IS a warning.
- "Export", "schade" (damage), "niet rijdend" (not drivable), missing APK are genuine warnings."""
        elif country_code == "de":
            desc_context = """
IMPORTANT — German market context for reading descriptions:
- "Unfallfahrzeug" or "Unfallwagen" means accident/damaged vehicle — this IS a warning.
- "Bastlerfahrzeug" or "für Bastler" means it needs significant work — warning.
- "Export" means the car is sold for export only, often with issues.
- "HU/AU neu" or "TÜV neu" means freshly inspected — positive sign.
- "Scheckheftgepflegt" means full dealer service history — positive.
- "Vorbesitzer" = previous owners. "1. Hand" = first owner."""
        elif country_code == "be":
            desc_context = """
IMPORTANT — Belgian market context for reading descriptions:
- Belgium has NL and FR speaking regions. Descriptions may be in Dutch or French.
- "Eerste eigenaar" / "Premier propriétaire" = first owner.
- "Ongevalvrij" / "Sans accident" = no accidents — positive.
- "Keuring geldig" / "Contrôle technique valable" = valid inspection — positive.
- "Schade" / "Dommage" = damage — warning.
- Cars in Belgium are often cheaper due to tax structures."""

    prompt = f"""You are a used car pricing expert for the {country_name} market (AutoScout24 {site_suffix}).

Car details:
- {data.make} {data.model}, {data.year} ({car_age} years old)
- {data.mileage:,} km ({mileage_per_year:,} km/year — {"above" if mileage_per_year > avg_mileage_per_year else "below"} average of ~15,000 km/year)
- Fuel: {data.fuel}, Transmission: {data.transmission}
{f"- Power: {data.power_kw} kW" if data.power_kw else ""}

Pricing:
- Our model predicts this car is worth: €{data.predicted_price:,}
- The seller is asking: €{data.actual_price:,}
- Difference: {data.diff_pct:+.1f}% ({"seller asks less than predicted" if data.diff_pct < 0 else "seller asks more than predicted"})
{f"- Average {data.make} {data.model} ({data.year-2}–{data.year+2}) in our database: €{avg_price:,}" if avg_price else ""}

Prediction accuracy: {confidence_text}
{listing_details}

Write 2-3 concise sentences explaining why this car might be {"underpriced (a good deal)" if data.diff_pct < 0 else "overpriced"} or whether the price seems {"justified despite being below" if data.diff_pct < 0 else "justified despite being above"} the predicted value. Consider mileage relative to age, model popularity, and fuel type trends in the {country_name} market. If prediction accuracy is low, mention that the estimate is less reliable.
{desc_context}

Only start with "⚠️ Warning:" if there is a GENUINE concern like: replaced odometer with different actual mileage than listed, undisclosed damage, accidents, export-only status, or missing inspection. Do NOT warn about normal import history or partial ownership details.

{"Reference specific details from the listing description or equipment where relevant. Mention notable issues (known defects, missing maintenance) and positives (full service history, new parts)." if listing_details else ""} Be direct and helpful — this is for a car buyer. Write in English."""

    # Kill-switch: set LLM_DISABLED=1 on Railway to instantly disable /explain
    # without removing the API key. Useful when burning down quota.
    if os.environ.get("LLM_DISABLED") == "1":
        return {"explanation": None, "error": "disabled",
                "message": "AI overview is temporarily disabled."}

    try:
        client = get_openai()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=200,
            temperature=0.7,
        )
        explanation = response.choices[0].message.content.strip()
        return {"explanation": explanation}
    except Exception as e:
        # Graceful fallback so the extension can render a useful message instead
        # of a mysterious 502. Common failure: OpenAI quota exhausted.
        msg = str(e)
        if "insufficient_quota" in msg or "exceeded your current quota" in msg:
            reason = "quota"
            user_msg = "AI overview is temporarily unavailable (billing)."
        elif "rate_limit" in msg.lower() or "429" in msg:
            reason = "rate_limit"
            user_msg = "AI overview is rate-limited, try again in a minute."
        else:
            reason = "error"
            user_msg = "AI overview is temporarily unavailable."
        return {"explanation": None, "error": reason, "message": user_msg,
                "detail": msg[:200]}


# ── Detailed prediction endpoint (premium) ───────────────────────────────────
class DetailedInput(BaseModel):
    make: str
    model: str
    year: int
    mileage: int
    fuel: str
    transmission: str
    power_kw:        Optional[int] = None
    predicted_price: int                     # base prediction already computed
    actual_price:    Optional[int] = None
    description:     Optional[str] = None
    equipment:       Optional[List[str]] = None
    photo_count:     Optional[int] = None

@app.post("/predict/detailed")
@limiter.limit("10/minute")
def predict_detailed(request: Request, car: DetailedInput):
    base_price = car.predicted_price

    # Ask LLM for adjustment based on description + equipment
    adjustment_pct = 0
    explanation = ""

    has_extra = car.description or car.equipment
    if has_extra:
        car_age = CURRENT_YEAR - car.year
        mileage_per_year = round(car.mileage / max(car_age, 1))
        equipment_str = ", ".join(car.equipment) if car.equipment else "Not listed"

        prompt = f"""You are a used car valuation expert for the Dutch market.

A machine learning model predicted this car's market value at €{base_price:,}. Your job is to adjust this prediction based on listing details that the model cannot see.

Car: {car.make} {car.model} {car.year}, {car.mileage:,} km ({mileage_per_year:,} km/year), {car.fuel}, {car.power_kw or "?"} kW
{f"Asking price: €{car.actual_price:,}" if car.actual_price else ""}

Seller description:
{car.description or "No description provided"}

Equipment: {equipment_str}
Photos: {car.photo_count or "unknown"}

Based on the description and equipment, provide a price adjustment percentage.

Positive adjustments for: full service history, single owner, factory warranty, accident-free, many premium features, lots of photos, well-maintained.
Negative adjustments for: mentions of damage/accidents, export-only, missing APK (MOT), sparse description/few photos, high owner count.

Respond with ONLY a JSON object, no other text:
{{"adjustment_pct": <number between -15 and +15>, "reasoning": "<1-2 sentences>"}}"""

        try:
            client = get_openai()
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=150,
                temperature=0.3,
                response_format={"type": "json_object"},
            )
            import json
            parsed = json.loads(response.choices[0].message.content)
            adjustment_pct = max(-15, min(15, float(parsed.get("adjustment_pct", 0))))
            explanation = parsed.get("reasoning", "")
        except Exception:
            pass  # Fall back to base prediction if LLM fails

    adjusted_price = int(base_price * (1 + adjustment_pct / 100))

    result = {
        "predicted_price": adjusted_price,
        "base_price":      base_price,
        "adjustment_pct":  round(adjustment_pct, 1),
        "explanation":     explanation,
    }

    if car.actual_price:
        diff_pct = (car.actual_price - adjusted_price) / adjusted_price * 100
        result["actual_price"] = car.actual_price
        result["diff_pct"]     = round(diff_pct, 1)
        result["diff_eur"]     = car.actual_price - adjusted_price

    return result


# ── Price history endpoint (premium) ─────────────────────────────────────────
class MarketTrendInput(BaseModel):
    make: str
    model: str
    year: int

@app.post("/market-trend")
@limiter.limit("30/minute")
def market_trend(request: Request, car: MarketTrendInput):
    """Average price trend for similar cars (same make/model, ±2 years)."""
    try:
        con = sqlite3.connect(DB_PATH)
        rows = con.execute("""
            SELECT
                strftime('%Y-%m', scraped_at) AS month,
                AVG(price) AS avg_price,
                COUNT(*) AS count
            FROM listings
            WHERE make = ? AND model = ? AND year BETWEEN ? AND ?
            GROUP BY month
            ORDER BY month
        """, (car.make, car.model, car.year - 2, car.year + 2)).fetchall()
        con.close()
    except Exception:
        return {"trend": []}

    trend = [{"month": r[0], "avg_price": int(r[1]), "count": r[2]} for r in rows if r[0]]
    return {"trend": trend, "make": car.make, "model": car.model}


# ── Similar cars endpoint ─────────────────────────────────────────────────────
class SimilarCarsInput(BaseModel):
    make: str
    model: str
    year: int
    mileage: int
    actual_price: int
    predicted_price: int
    listing_id: Optional[str] = None
    country: Optional[str] = "NL"

@app.post("/similar-cars")
@limiter.limit("30/minute")
def similar_cars(request: Request, car: SimilarCarsInput):
    """Find similar listings and rank by best deal (actual vs predicted price)."""
    country_upper = (car.country or "NL").upper()
    try:
        con = sqlite3.connect(DB_PATH)
        rows = con.execute("""
            SELECT id, price, year, mileage, fuel, transmission,
                   power_kw, range_km, trim_id, variant_id,
                   generation_id, seller_type, location, country
            FROM listings
            WHERE make = ? AND model = ? AND year BETWEEN ? AND ?
              AND (country = ? OR country IS NULL)
        """, (car.make, car.model, car.year - 2, car.year + 2, country_upper)).fetchall()
        con.close()
    except Exception:
        return {"similar": [], "rank": None, "total": 0}

    if not rows:
        return {"similar": [], "rank": None, "total": 0}

    # Build feature dicts and predict all at once
    similar = []
    for r in rows:
        lid, price, year, mileage, fuel, transmission, power_kw, range_km, \
            trim_id, variant_id, generation_id, seller_type, location, country = r
        car_age = CURRENT_YEAR - year
        country = country or car.country or "NL"
        fuel = fuel or "Unknown"
        # Build URL based on country domain
        domain = get_country_config(country)["domain"]
        similar.append({
            "id": str(lid),
            "price": price,
            "year": year,
            "mileage": mileage,
            "fuel": fuel,
            "location": location or "",
            "url": f"https://{domain}/aanbod/-/-{lid}",
            "_features": {
                "car_age": car_age,
                "mileage": mileage,
                "power_kw": power_kw,
                "range_km": range_km,
                "mileage_per_year": mileage / max(1, car_age),
                "is_electric": int(bool(re.match(r"(?i)^elektr", fuel))),
                "is_hybrid": int(bool(re.search(r"(?i)elektro/|hybrid|/elektr", fuel))),
                "make": car.make,
                "model": car.model,
                "trim_id": trim_id or "Unknown",
                "variant_id": variant_id or "Unknown",
                "generation_id": generation_id or "Unknown",
                "fuel": fuel,
                "transmission": transmission or "Unknown",
                "seller_type": seller_type or "Unknown",
                "country": country,
            },
        })

    # Batch predict all similar cars
    features_df = pd.DataFrame([s["_features"] for s in similar])
    predicted_prices = np.expm1(get_pipeline().predict(features_df)).astype(int)

    for s, pred in zip(similar, predicted_prices):
        s["predicted_price"] = int(pred)
        s["diff_pct"] = round((s["price"] - pred) / pred * 100, 1)
        del s["_features"]

    # Sort by diff_pct: most underpriced first (best deals)
    similar.sort(key=lambda s: s["diff_pct"])

    # Find rank of current listing
    total = len(similar)
    current_diff = (car.actual_price - car.predicted_price) / car.predicted_price * 100 if car.predicted_price else 0
    rank = None
    for i, s in enumerate(similar):
        if car.listing_id and s["id"] == car.listing_id:
            rank = i + 1
            break
    if rank is None:
        rank = sum(1 for s in similar if s["diff_pct"] < current_diff) + 1

    # Return top 30 best deals (excluding current listing) — extension will
    # live-check each URL in parallel and display up to 3 that are still active.
    # Fetching 30 gives lots of headroom when DB is stale and many have sold.
    best_deals = [s for s in similar if s.get("id") != car.listing_id][:30]

    return {
        "similar": best_deals,
        "rank": rank,
        "total": total,
    }


# ── Temporary file upload endpoint ───────────────────────────────────────────
# Upload cars.db or pipeline.joblib to the server.
# Protected by a simple secret token via UPLOAD_SECRET env var.
# Remove this endpoint once you have a proper deployment pipeline.
from fastapi import UploadFile, File, Header
import shutil

UPLOAD_SECRET = os.environ.get("UPLOAD_SECRET", "")

@app.post("/upload/{filename}")
async def upload_file(
    filename: str,
    file: UploadFile = File(...),
    authorization: str = Header(None),
):
    if not UPLOAD_SECRET or authorization != f"Bearer {UPLOAD_SECRET}":
        raise HTTPException(status_code=403, detail="Invalid or missing UPLOAD_SECRET")

    range_path = os.path.join(os.path.dirname(MODEL_PATH), "range_lookup.json")
    allowed = {"cars.db": DB_PATH, "pipeline.joblib": MODEL_PATH, "range_lookup.json": range_path}
    if filename not in allowed:
        raise HTTPException(status_code=400, detail=f"Only {list(allowed.keys())} allowed")

    dest = allowed[filename]
    # Write to a temp file first, then move atomically
    tmp = dest + ".tmp"
    with open(tmp, "wb") as f:
        shutil.copyfileobj(file.file, f)
    os.replace(tmp, dest)

    # Reload model if pipeline was updated
    if filename == "pipeline.joblib":
        global _pipeline
        _pipeline = None  # force reload on next request

    size_mb = os.path.getsize(dest) / (1024 * 1024)
    return {"status": "ok", "file": filename, "size_mb": round(size_mb, 1), "path": dest}


# ── Mirror download endpoint ─────────────────────────────────────────────────
# Lets the resell dashboard (and any other client with the secret) pull the
# weekly-retrained artifacts back from Railway. Same bearer-token guard as the
# upload endpoint; same allowlist of files.
from fastapi.responses import FileResponse


@app.get("/download/{filename}")
def download_file(filename: str, authorization: str = Header(None)):
    if not UPLOAD_SECRET or authorization != f"Bearer {UPLOAD_SECRET}":
        raise HTTPException(status_code=403, detail="Invalid or missing UPLOAD_SECRET")

    range_path = os.path.join(os.path.dirname(MODEL_PATH), "range_lookup.json")
    allowed = {"cars.db": DB_PATH, "pipeline.joblib": MODEL_PATH, "range_lookup.json": range_path}
    if filename not in allowed:
        raise HTTPException(status_code=400, detail=f"Only {list(allowed.keys())} allowed")

    src = allowed[filename]
    if not os.path.exists(src):
        raise HTTPException(status_code=404, detail=f"{filename} not on server yet")

    return FileResponse(src, filename=filename, media_type="application/octet-stream")
